feat: create template pull request
saigon-technology/rn-base-component pull request #14
Opened 2023-02-27 04:22 UTC by TranQuangPhi

## Summary
- add template pull request

## Features
- None

## Bugs
- None

## Check List
- [x] Your code builds clean without any errors or warnings.
- [x] Check coding convention.

## Proof of Completeness
- None

2023-02-27 07:30 UTC, loc-nguyenthien requested changes

2023-02-27 07:30 UTC, loc-nguyenthien commented on .github/pull_request_template.md
> +
Add some description in these field for user to edit (noted to remove if unnecessary)

2023-02-27 09:48 UTC, loc-nguyenthien approved these changes

2023-03-03 07:00 UTC, TranQuangPhi commented on .github/pull_request_template.md
> +- [ ] Check coding convention.
added

2023-03-07 09:01 UTC, ThinhKimVo approved these changes

2023-03-28 13:35 UTC, honghoangsts approved these changes

2023-03-28 13:35 UTC, merged